
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_sf_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_sf_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:

  +transient: false
  
  dbt_sf_project:

    customers_stg:
      +schema: L2_PROCESSING

    orders_stg:
      +schema: L2_PROCESSING

    orderitems_stg:
      +schema: L2_PROCESSING

    orders_fact:
      +schema: L2_PROCESSING
      +materialized: table

    customerrevenue:
      +materialized: table